openapi: 3.0.3
info:
  title: API do repositório de políticas públicas
  description: api para controlar a logica de negócio do site
  version: 0.0.1
  termsOfService: http://localhost:3030
  contact:
    name: developer
    email: workguisantos@gmail.com
  license:
    name: "MIT"
servers:
  # Pode ter quantos servidores forem necessário (Produção + Teste)
  - url: http://localhost:3030
    description: API de teste
paths:
  /login:
    get:
      summary: recupera todos os logins
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/logins"
  /login/{id}:
    # O parâmentro nessa área permitirá utilizá-lo para todos os verbos nesta rota
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true

    get:
      summary: recupera um login por ID
      # Lugar possível de colocar o parametro, mas servirá apenas para o verbo get
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                # usando por conponente
                $ref: "#/components/schemas/login"
        404:
          description: login não encontrado
          content:
            application/json:
              example: "Not Found"
    post:
      summary: cria um novo login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                senha:
                  type: string
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                # usando por conponente
                $ref: "#/components/schemas/login"
        404:
          description: login não encontrado
          content:
            application/json:
              example: "Not Found"
    put:
      summary: update de um login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                senha:
                  type: string
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                # usando por conponente
                $ref: "#/components/schemas/login"
        404:
          description: login não encontrado
          content:
            application/json:
              example: "Not Found"
    delete:
      summary: delete de um login
      responses:
        200:
          description: "Sucesso"
          content:
            application/json:
              example: Success
        404:
          description: login não encontrado
          content:
            application/json:
              example: "Not Found"
              
  #Rotas para publicações
  /publicacoes:
    get:
      tags:
        - Publicações
      summary: Recupera todas as publicações
      responses:
        200:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/publicacoes"
        404:
          description: "Não foi possível acessar o banco de dados"
          content:
            application/json:
              example: "Connection Error"
    
    post:
      tags:
        - Publicações
      summary: Cadastra uma nova publicação
      requestBody: 
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/publicacao_put"

      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/publicacao"

        404:
          description: "Não foi possível inserir a publicação"
          content:
            application/json:
              example: Not Found
              
        409:
          description: "Publicação existente"
          content: 
            application/json:
              example: Conflict

  /publicacoes/{id}:
    parameters:
      - name: id
        in: path
        schema: 
          type: integer
        required: true
    get:
      tags:
        - Publicações
      summary: Recupera publicação por ID
      responses:
        '200':
          description: "Sucesso"
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/publicacao'
        '404':
          description: "Publicação não encontrada"
          content:
            application/json:
              example: Not Found
    
    put:
      tags:
        - Publicações
      summary: Atualiza publicacao pelo ID

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/publicacao_put'

      responses:
        '200':
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publicacao'
                
        '204':
          description: "Sem alteração"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publicacao'
                
        '404':
          description: "Publicação não encontrada"
          content:
            application/json:
              example: Not Found
              
    delete:
      tags:
        - Publicações
      summary: Apaga publicação por ID
      responses:
        '200':
          description: "Sucesso"
          content:
            application/json: 
              example: Deleted
        '404':
          description: "Publicação não encontrada"
          content:
            application/json:
              example: Not Found


security:
  - auth: []

components:
  schemas:
    login:
      type: object
      properties:
        id:
          type: integer
        login:
          type: string
        senha:
          type: string
        ativo:
          type: boolean
          # Lembrando que string pode ter outros formatos Ex. (format: date-time; format: currency)
    logins:
      type: array
      items:
        $ref: "#/components/schemas/login"

    publicacao:
      type: object
      properties:
        id:
          type: integer
        data:
          type: string
        titulo:
          type: string
        registro:
          type: string
        tipo:
          type: string
        usuarioId:
          type: integer

    publicacao_put:
      type: object
      properties:
        data:
          type: string
        titulo:
          type: string
        registro:
          type: string
        tipo:
          type: string
        usuarioId:
          type: integer

    publicacoes:
      type: array
      items:
        $ref: "#/components/schemas/publicacao"

  securitySchemes:
    auth:
      type: http
      # tipo Token do portador
      scheme: bearer
      bearerFormat: JWT
